### ISSUE TITLE
name of restruant menu

### ISSUE THREAD

**Issue by mwang840** [andrewango/restaurant-menu#109]
Minor issue but a unique name with the menu would look cool
<img width="281" alt="image" src="https://user-images.githubusercontent.com/90732327/236647094-131609bf-2b0f-4303-9757-13fd1d7b864b.png">

**Comment by cfrashure** [comment]
Team 13 is a great name!
(The title bar has something a little more formal, too :))

**Comment by andrewango** [comment]
RISTORANTEE CALDOOO!!!!!

**Comment by mwang840** [comment]
Sounds like a good name Andrew, for your project. I'll go ahead and close this minor issue : )
